tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "jesseduffield/lazygit"
tap "romkatv/powerlevel10k"
echo "source $(brew --prefix)/opt/powerlevel10k/powerlevel10k.zsh-theme" >>~/.zshrc
brew "fd"
brew "git"
brew "maven"
brew "neovim"
brew "openjdk@11"
brew "ripgrep"
brew "tmux"
brew "jesseduffield/lazygit/lazygit"
brew "romkatv/powerlevel10k/powerlevel10k"
